apiVersion: v1
kind: Secret
metadata:
  name: discord-ms-secrets
type: Opaque
stringData:
  DISCORD_BOT_TOKEN: replace-me
  DATABASE_URL: mongodb+srv://user:password@cluster.mongodb.net/discord_service
